### PR TITLE
feat: support style hot update

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
close: #12

### CODE REVIEW

**Comment by baiwusanyu-c** [comment]
TODO: unit test

**Comment by baiwusanyu-c** [comment]
The test code refers to the test code implementation of `@vitejs/plugin-vue`

**Comment by ShenQingchuan** [comment]
> The test code refers to the test code implementation of `@vitejs/plugin-vue`

That's amazing contribution and I'd like to invite you to be my co-founder! I'm really lack of HMR knowledge and practice experience.

**Comment by baiwusanyu-c** [comment]
Wow, that was my pleasure.
This test code runs under windows. The second unit test (`getColor` function) sometimes reports an error, but it does not report an error on macos. I am still thinking about how to improve this e2e test

Also, I noticed a couple of issues, I haven't tested are they implemented, or are they planned?
1. css v-bind support
2. There seems to be no way to debug in .vine.ts
3. Support web Componet

**Pull request merged**
