### PR TITLE
feat(language-server): generate template virtual code

### PR DESCRIPTION
**Pull request by johnsoncodehk**
This is a new draft implementation of Vue Vine language services by Volar 2.

- [x] Support variable reference and click jumping into definition.

- [ ] Migrate to TS plugin to resolve component types to support props intellisense and be compatible with SFC components.

### CODE REVIEW

**Comment by ShenQingchuan** [comment]
@johnsoncodehk 

Awesome work !! Thanks for joining us and make this epic PR, here's my feedback after trying this PR's effect.

image

There are three questions here.
1. The first question is: `_unref` requires external import, I see you left a comment of Todo in the code, do you need the compiler of Vue Vine or other parts to do any additional support?

    Also, the mapping from `_unref(loading)` to original `loading` is broken and dislocated

2. The second question is: The `@click="...some bare expression"` seems not detected by template generation process, and there's not any segement about it in the final virtual code as well.

    Is this a compiler-dom bug or something we need to modify?

3. The third question may be related to Issue 1, those variables need to be wrapped with `_unref`.

**Comment by johnsoncodehk** [comment]
1. This was due to the `mode: 'module'` option being passed in, I disabled it in https://github.com/johnsoncodehk/vue-vine/commit/84133d1deb7556229a62708321603c88f02a5965 which seemed to fix the mapping issue.
2. This is also fixed by remove ``mode: 'module'`` option.
3. It's implement by https://github.com/johnsoncodehk/vue-vine/commit/421ec369e54c3d2a8f1018110ed5a6e9c1d7b1aa.

**Comment by ShenQingchuan** [comment]
> 1. This was due to the `mode: 'module'` option being passed in, I disabled it in [johnsoncodehk@84133d1](https://github.com/johnsoncodehk/vue-vine/commit/84133d1deb7556229a62708321603c88f02a5965) which seemed to fix the mapping issue.
> 2. This is also fixed by remove `mode: 'module'` option.
> 3. It's implement by [johnsoncodehk@421ec36](https://github.com/johnsoncodehk/vue-vine/commit/421ec369e54c3d2a8f1018110ed5a6e9c1d7b1aa).

Thanks for such detailed explanation 🙏！！

After trying the new commits, I‘ve got some new questions:

1. It's interesting that variables `id` and `isDark` which are been referenced didn't show any warning of `ts(6133) declared but not used`, but why do those functions `toggleDark` and `randomString` get warnings?

image

2. The last question is what am I supposed to do (maybe add more API from compiler) to support component props typing when user're writing components in template.

I've talked this with @so1ve  in #53 , I think I can provide a feature-specific API for this

All I wanna achieve is to fix #52 #53 , and I think the basic features of Vue Vine language service are done.

**Comment by ShenQingchuan** [comment]
@johnsoncodehk As mentioned in #53, as long as we need type definitions fromuser source code, we can easily read them on `VineCompFnCtx`, every component context stores a Record of prop name and it's typing source code babel node, so that we can use it's location and copy it into final virtual code for Volar

**Comment by johnsoncodehk** [comment]
From https://github.com/volarjs/insiders/issues/3

> I gave it a try in https://github.com/vue-vine/vue-vine/pull/69/commits/e126df40c4e6cb213523ef6ba43c416517746fbf
> 
> But it seems that nothing has changed after I write contributes.typescriptServerPlugin this into `@vue-vine/vscode-ext` package.json

There is a fews problems.

1. The ts plugin should be export with `export = ` instead of `export default`
2. tsup config incorrect
3. The way Volar patches `languageServiceHost` for `.vine.ts` is incorrect

For 3. I will update a version for Volar first.

> By the way, I found in `vue/language-tools` that many intellisense feature in Vue SFC template is done by creating Volar Service Plugin, I'm wondering if we can adopt it into Vue Vine ?

Yes it is possible, let's see after completing the TS plugin.

**Comment by ShenQingchuan** [comment]
@johnsoncodehk  I got many Errors in every `.vine.ts` after the latest commit, is that because those globalTypes and TS service are not completely loaded?

**Comment by johnsoncodehk** [comment]
> @johnsoncodehk I got many Errors in every `.vine.ts` after the latest commit, is that because those globalTypes and TS service are not completely loaded?

Can you reproduce the problem in the playground directory?

**Comment by ShenQingchuan** [comment]
> > @johnsoncodehk I got many Errors in every `.vine.ts` after the latest commit, is that because those globalTypes and TS service are not completely loaded?
> 
> Can you reproduce the problem in the playground directory?

@johnsoncodehk  Yes, for now if I want to verify our results for language service support, I'll do:
1. run build script in the root directory, 
2. click VSCode's Debug panel -> "Run Vine extension”
3. The extension debug host window automatically opens `packages/playground`, and I'll open `src/vine/app.vine.ts` to see the syntax highlight & TS semantics diagnoses

image

**Comment by johnsoncodehk** [comment]
This seems to be https://github.com/vuejs/language-tools/issues/3942, which may be related to the extensions you installed.
https://github.com/vuejs/language-tools/issues/3942

**Comment by ShenQingchuan** [comment]
> This seems to be [vuejs/language-tools#3942](https://github.com/vuejs/language-tools/issues/3942), which may be related to the extensions you installed.
> 
> This issue cannot be avoided from us and I will discuss this with the TS team.

Thanks a lot !!!!

After switching from my Linux PC to my Mac, there's indeed not these diagnoses occurred.

Everything looks pretty fine now.

So I'll merge this PR, and we can open new PRs for further extension features later.

**Comment by ShenQingchuan** [comment]
@johnsoncodehk It seems like that I meet some problems with VSCode extension bundling that after packing out a `.vsix` file, installing locally and opening a `.vine.ts`, I found there's not a `Vine Language Server` in "Output" panel.

Can easily reproduce in `main` branch now with the same operations.

**Pull request merged**
