### PR TITLE
feat(vscode-ext): add snippets

### PR DESCRIPTION
**Pull request by wzc520pyfm**
### Snippets

* `vcf`: means `v(ine) c(omponent) f(unction)`

   For quick inserting a component function

   https://github.com/user-attachments/assets/5b0a875a-4cbb-4c3a-8fa0-e065669330ca

* `vtpl`: means `v(ine) t(em)pl(ate)`

   For quick inserting a vine\`...\` with a prettier-formated new line inside it

   Preview image: 
   
   https://github.com/user-attachments/assets/7fd0787b-a36a-4dbf-a4ed-7976bc8ec84f

* `vsty`: means `v(ine) sty(le)`

   For quick inserting a vineStyle(...)

   Preview image: 
   
   https://github.com/user-attachments/assets/427af17b-71e6-42d3-b64b-11d020eb796a

* `vstysc`: means `v(ine) sty(le) sc(oped)`

   For quick inserting a vineStyle.scoped(...)

   Preview image: 
   
   https://github.com/user-attachments/assets/64d4dd5a-cf52-4fc1-b2f7-090c67804afe

* `vpr`: means `v(ine) pr(op)`

   For quick inserting a `const ${2:propName} = vineProp<$1>($3)`

   Preview image:

   https://github.com/user-attachments/assets/d3f509fa-33d3-412c-a868-8262ba0d7c23

* `vprdf`: means `v(ine) pr(op) with d(e)f(ault)`

   For quick inserting a `const ${1:propName} = vineProp.withDefault($2)`

   Preview image:

   https://github.com/user-attachments/assets/9523a1a0-0bcc-48b0-bd73-01120f1b098c

* `vpr?`: means `v(ine) pr(op) (optional)`

   For quick inserting a `const ${1:propName} = vineProp.optional<$2>($3)`

   Preview image:

   https://github.com/user-attachments/assets/934b3047-c8e8-4c34-be65-d1dfbc588481

* `vemt`: means `v(ine) em(i)t(s)`

   For quick inserting a `const ${1:emits} = vineEmits<$2>()`

   Preview image:
   
   https://github.com/user-attachments/assets/829ddd99-b305-41ce-8baa-b8aa18001e9f

### CODE REVIEW

**Comment by ShenQingchuan** [comment]
Hey! 😍 Thanks for your enthusiasm and contribution to Vue Vine, this feature is mentioned in our TodoTask kanban #75, and it's really important to improving user editing experience!

The changes you've made now is a really good start !! But I'm willing to discuss more about it in this thread.

### Conventions

There're some rules we're supposed to follow for this task:

1. Since built-in intellisense item like variables, type names need to be prioritized in the list, we need to create snippets with special `"prefix"`, maybe some consonant combinations without vowels like these:
    - `vtpl`: means `v(ine) t(em)pl(ate)`

        For quick inserting a vine\`...\` with a prettier-formated new line inside it

        Preview image: ... 

    - `vsty`: means `v(ine) sty(le)`

        For quick inserting a `vineStyle(...)`

        Preview image: ... 
    
    - `vstysc`: means `v(ine) sty(le) sc(oped)`

        For quick inserting a `vineStyle.scoped(...)`

        Preview image: ... 

As for those pre-processor languages, I hold the opinion that user may be able to tolerate typing their names, after all, their names are not long, and the longest is stylus (5 letters). If you're willing to add them with well-designed prefix names, you can just add it to our collection! 💗

How about continuing this PR ~ ? We're looking forward to more thoughts from you !!

**Review by ShenQingchuan — CHANGES_REQUESTED** [review]
How about continuing this PR ~ ? We're looking forward to more thoughts from you !!

**Comment by wzc520pyfm** [comment]
@ShenQingchuan I agree with your suggestion! I will convert this PR to draft and continue to add more snippets. And I also look forward to your more suggestions at any time.

**Comment by ShenQingchuan** [comment]
Hi @wzc520pyfm ~
I suggest that we can add one more "slot" (maybe that name? I'm not sure about how to call the "$0", "$1")

for the `vsty` and `vstysc`, located just before the template string, in order to facilitate users to quickly adjust the CSS class language prefix.

**Comment by ShenQingchuan** [comment]
For props snippets, I suggest:

- `vpr` for inserting: `const propName($2) = vineProp<$1>($3)`

The reason I wanna delete the last `p` in your proposal is that inserting single prop must be a high frequent action, so I'd like to decrease the letter user needs to type as much as possible.

- `vpr?` for inserting `const ${1:propName} = vineProp.optional<$2>($3)`
- `vprdf` for inserting `const ${1:propName} = vineProp.withDefault($2)`

**Comment by wzc520pyfm** [comment]
Maybe `vpr` can keep the slot order same with `vpr?` ?

~`vpr` for inserting: `const propName($2) = vineProp<$1>($3)`~

`vpr` for inserting: `const propName($1) = vineProp<$2>($3)`

**Review by ShenQingchuan — APPROVED** [review]

**Pull request merged**
